name: Security & License Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write  # required for SARIF upload
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Install cargo-audit
      run: cargo install --git https://github.com/cosmir17/rustsec --branch sarif-support cargo-audit
    - name: Run vuln scan
      run: cargo audit --format sarif > scan.sarif

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: scan.sarif
