name: Security & License Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write  # required for SARIF upload
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Trivy (vuln scan)
      run: |
        trivy fs . --scanners vuln --format sarif --output trivy.sarif

    - name: Upload Trivy SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy.sarif
