#!/bin/bash

set -e


function test_toolkit_show_seed() {

    local TARGET_ENV=$1

    # Start the toolkit container
    bash toolkit-start $TARGET_ENV $NODE_TAG

    SHOW_SEED_UNDEPLOYED=$(bash toolkit-show-seed 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon diesel' | tr -d '\n\r' | xargs)
    SHOW_SEED_UNDEPLOYED=$(bash toolkit-show-seed 'a14c6b19e770dbf6ca3199a223abb711013ea6edb63b3eb110d8c28aacbeae2d4598f90a3d27d8077baa07405ae00c253b706e5f61e89dfb6b5ac18d58d57141' | tr -d '\n\r' | xargs)
    echo "Generated seed for undeployed: ${SHOW_SEED_UNDEPLOYED}"
    if [[ $SHOW_SEED_UNDEPLOYED == "0000000000000000000000000000000000000000000000000000000000000001" ]]; then
        echo -e "\033[0;32m✔\033[0m The generated seed is valid "
    else    
        echo -e "\033[0;31m✘\033[0m The generated seed is invalid"
    fi
    echo ""

    # Stop the toolkit container
    bash toolkit-cleanup
}

test_toolkit_show_seed "undeployed" ;