#!/bin/bash

set -e

# Start the toolkit container
bash scripts/toolkit-start undeployed
bash scripts/toolkit-start devnet
bash scripts/toolkit-start testnet02
bash scripts/toolkit-start nodedev01

# Show the address
SHOW_ADDRESS_UNDEPLOYED_SHIELDED=$(bash scripts/toolkit-show-address undeployed shielded 0000000000000000000000000000000000000000000000000000000000000001)
SHOW_ADDRESS_NODEDEV01_SHIELDED=$(bash scripts/toolkit-show-address nodedev01 shielded 0000000000000000000000000000000000000000000000000000000000000001)
SHOW_ADDRESS_DEVNET_SHIELDED=$(bash scripts/toolkit-show-address devnet shielded 0000000000000000000000000000000000000000000000000000000000000001)
SHOW_ADDRESS_TESTNET02_SHIELDED=$(bash scripts/toolkit-show-address testnet02 shielded 0000000000000000000000000000000000000000000000000000000000000001)
SHOW_ADDRESS_UNDEPLOYED_UNSHIELDED=$(bash scripts/toolkit-show-address undeployed unshielded 0000000000000000000000000000000000000000000000000000000000000001)
SHOW_ADDRESS_NODEDEV01_UNSHIELDED=$(bash scripts/toolkit-show-address nodedev01 unshielded 0000000000000000000000000000000000000000000000000000000000000001)
SHOW_ADDRESS_DEVNET_UNSHIELDED=$(bash scripts/toolkit-show-address devnet unshielded 0000000000000000000000000000000000000000000000000000000000000001)
SHOW_ADDRESS_TESTNET02_UNSHIELDED=$(bash scripts/toolkit-show-address testnet02 unshielded 0000000000000000000000000000000000000000000000000000000000000001)

echo "Generated address for undeployed shielded: ${SHOW_ADDRESS_UNDEPLOYED_SHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_UNDEPLOYED_SHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""

echo "Generated address for nodedev01 shielded: ${SHOW_ADDRESS_NODEDEV01_SHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_NODEDEV01_SHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""

echo "Generated address for devnet shielded: ${SHOW_ADDRESS_DEVNET_SHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_DEVNET_SHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""

echo "Generated address for testnet shielded: ${SHOW_ADDRESS_TESTNET02_SHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_TESTNET02_SHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""

echo "Generated address for undeployed unshielded: ${SHOW_ADDRESS_UNDEPLOYED_UNSHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_UNDEPLOYED_UNSHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""

echo "Generated address for nodedev01 unshielded: ${SHOW_ADDRESS_NODEDEV01_UNSHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_NODEDEV01_UNSHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""

echo "Generated address for devnet unshielded: ${SHOW_ADDRESS_DEVNET_UNSHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_DEVNET_UNSHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""

echo "Generated address for testnet02 unshielded: ${SHOW_ADDRESS_TESTNET02_UNSHIELDED:0:30}..."
if [[ $SHOW_ADDRESS_TESTNET02_UNSHIELDED == mn* ]]; then
    echo -e "\033[0;32m✔\033[0m The generated address is valid "
else    
    echo -e "\033[0;31m✘\033[0m The generated address is invalid"
fi
echo ""
echo "All addresses are valid (note, this is not valid in the bech32m format)"

bash scripts/toolkit-cleanup undeployed &
bash scripts/toolkit-cleanup devnet &
bash scripts/toolkit-cleanup testnet02 &
bash scripts/toolkit-cleanup nodedev01 &

wait