#!/bin/bash

set -e

CHAIN=$1
if [ "$CHAIN" != "undeployed" ] && [ "$CHAIN" != "devnet" ] && [ "$CHAIN" != "testnet02" ] && [ "$CHAIN" != "nodedev01" ]; then
    echo "Please provide a valid chain id (undeployed, devnet, testnet02, nodedev01)"
    echo "Usage: $0 <chain_id>"
    exit 1
fi

docker exec -it toolkit-${CHAIN} \
    /midnight-node-toolkit $2 $3 --help 