#!/bin/bash

set -e

# Hardcoded NODE_TAG - adjust as needed
NODE_TAG="0.13.2-rc.2"

CHAIN=$1
if [ -z "$CHAIN" ]; then
    echo "Please provide a chain id"
    echo "Usage: $0 <chain_id> <seed>"
    exit 1
fi
if [ "$CHAIN" != "undeployed" ] && [ "$CHAIN" != "devnet" ] && [ "$CHAIN" != "testnet02" ] && [ "$CHAIN" != "nodedev01" ] && [ "$CHAIN" != "preview" ]; then
    echo "Please provide a valid chain id (undeployed, devnet, testnet02, nodedev01, preview)"
    echo "Usage: $0 <chain_id> <seed>"
    exit 1
fi

#Switch case for the chain id
case $CHAIN in
    "undeployed")
        CHAIN_URL="ws://localhost:9944"
        ;;
    "devnet")
        CHAIN_URL="wss://rpc.devnet.midnight.network"
        ;;
    "preview")
        CHAIN_URL="wss://rpc.preview.midnight.network"
        ;;
    "testnet02")
        CHAIN_URL="wss://rpc.testnet02.midnight.network"
        ;;
    "qanet")
        CHAIN_URL="wss://rpc.qanet.dev.midnight.network"
        ;;
    "nodedev01")
        CHAIN_URL="wss://rpc.node-dev-01.dev.midnight.network"
        ;;
esac

SEED=$2
if [ -z "$SEED" ]; then
    echo "Please provide a seed"
    echo "Usage: $0 <chain_id> <seed>"
    exit 1
fi

TARGET_DIR=/tmp/toolkit

mkdir -p $TARGET_DIR
mkdir -p $TARGET_DIR/.sync_cache-$CHAIN

docker run \
    --rm \
    --name toolkit-generate-txs-for-$CHAIN \
    --network host \
    -v /tmp/toolkit:/out \
    -v /tmp/toolkit/.sync_cache-$CHAIN:/.sync_cache \
    ghcr.io/midnight-ntwrk/midnight-node-toolkit:$NODE_TAG \
    generate-txs \
    --src-url $CHAIN_URL \
    --dest-url $CHAIN_URL  \
    batches -n 2 -b 20 \
    --funding-seed "$SEED"
