// This file is part of midnightntwrk/midnight-indexer
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The custom-unshielded-token sibling of night-transactions.test.ts: the same
// transfer scenario, against a contract-minted unshielded token instead of NIGHT.
// Both suites share every test through unshielded-transfer-scenario.ts, so the two
// token types cannot drift apart in coverage.
//
// It deliberately mirrors none of the NIGHT suite's dust tests: DUST is generated by
// holding NIGHT, so a custom unshielded token produces no dust events at all.
//
// A custom token is not on the chain from genesis — it has to be minted by a
// contract and put in the funding wallet. That provisioning is an environment
// concern, not something this suite does, so the suite skips (never fails) when the
// funding wallet holds no custom token it can spend.
//
// WHERE THE TOKEN COMES FROM. The suite asks the funding wallet what it can spend,
// at the moment it runs. It deliberately does NOT read
// `data/static/<env>/unshielded-token-types.jsonc`: that fixture is a chain-wide
// scan, so it says which custom token types exist and who held them at scan time,
// but it cannot establish that the wallet under test owns any of them now. An e2e
// transfer has to spend the token, so existence is not enough — ownership is, and
// only the live balance knows it. The fixture remains the right input for the
// query and subscription suites, which only need a token type that exists.
//
// Minting the token from the test itself, through the toolkit minter flow the
// wrapper already implements (deployMintSendUnshielded), is a known future option
// and was deliberately deferred — it would make every run deploy a contract.

import log from '@utils/logging/logger';
import '@utils/logging/test-logging-hooks';
import dataProvider from '@utils/testdata-provider';
import { listUnshieldedHoldings, pickSpendableCustomToken } from '@utils/moth/moth-holdings';
import {
  defineUnshieldedTransferTests,
  setupUnshieldedTransferScenario,
  UNSHIELDED_TRANSFER_TIMEOUT,
} from './unshielded-transfer-scenario';

const TRANSFER_AMOUNT = 1;

describe('unshielded custom token transactions', { timeout: UNSHIELDED_TRANSFER_TIMEOUT }, () => {
  const scenario = setupUnshieldedTransferScenario({
    label: 'CustomToken',
    // Placeholder: `prepare` below replaces it with the token the funding wallet can
    // actually spend, discovered from its live balance. Nothing reads this value
    // before `prepare` has run.
    tokenType: '',
    amount: TRANSFER_AMOUNT,
    unit: 'token',
    // Self-transfer: the minted supply is fixed, so sending to another wallet
    // would burn one unit per run until the suite silently starts skipping.
    selfTransfer: true,
    prepare: async (scenario) => {
      const holdings = await listUnshieldedHoldings(
        dataProvider.getFundingSeed(),
        scenario.wallet.source.address,
        scenario.toolkit,
      );
      log.debug(
        `Funding wallet holds ${holdings.size} unshielded token type(s): ` +
          [...holdings.entries()].map(([type, value]) => `${type}=${value}`).join(', '),
      );

      const tokenType = pickSpendableCustomToken(holdings, BigInt(TRANSFER_AMOUNT));
      if (tokenType === undefined) {
        return (
          'environment not provisioned: the funding wallet holds no custom unshielded ' +
          `token with more than ${TRANSFER_AMOUNT} spendable, so ${TRANSFER_AMOUNT} cannot ` +
          'be transferred leaving change behind. Mint one into the funding wallet.'
        );
      }

      // Assigned before the scenario submits the transfer, which happens once this
      // hook has returned.
      scenario.token.tokenType = tokenType;
      return null;
    },
  });

  defineUnshieldedTransferTests(scenario);
});
