// This file is part of midnightntwrk/midnight-indexer
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The custom-unshielded-token sibling of night-transactions.test.ts: the same
// transfer scenario, against a contract-minted unshielded token instead of NIGHT.
// Both suites share every test through unshielded-transfer-scenario.ts, so the two
// token types cannot drift apart in coverage.
//
// It deliberately mirrors none of the NIGHT suite's dust tests: DUST is generated by
// holding NIGHT, so a custom unshielded token produces no dust events at all.
//
// A custom token is not on the chain from genesis — it has to be minted by a
// contract and put in the funding wallet. That provisioning is an environment
// concern, not something this suite does, so the suite skips (never fails) when the
// environment has not been provisioned:
//   * no data/static/<env>/unshielded-token-types.jsonc, or no "custom" entry
//     -> the whole suite is skipped at collection;
//   * an entry exists but the funding wallet has no spendable balance of it
//     -> every test skips with an "environment not provisioned" reason.
// Minting the token from the test itself, through the toolkit minter flow the
// wrapper already implements (deployMintSendUnshielded), is a known future option
// and was deliberately deferred — it would make every run deploy a contract.

import log from '@utils/logging/logger';
import '@utils/logging/test-logging-hooks';
import dataProvider from '@utils/testdata-provider';
import {
  defineUnshieldedTransferTests,
  setupUnshieldedTransferScenario,
  UNSHIELDED_TRANSFER_TIMEOUT,
} from './unshielded-transfer-scenario';

const CUSTOM_TOKEN_TYPE = dataProvider.getUnshieldedTokenType('custom');

const DESTINATION_SEED = '0000000000000000000000000000000000000000000000000000000123456789';
const TRANSFER_AMOUNT = 1;

describe.skipIf(CUSTOM_TOKEN_TYPE === null)(
  'unshielded custom token transactions',
  { timeout: UNSHIELDED_TRANSFER_TIMEOUT },
  () => {
    const scenario = setupUnshieldedTransferScenario({
      label: 'CustomToken',
      // Safe: the describe above is skipped when the environment has no entry.
      tokenType: CUSTOM_TOKEN_TYPE!,
      amount: TRANSFER_AMOUNT,
      unit: 'token',
      destinationSeed: DESTINATION_SEED,
      prepare: async (scenario) => {
        // The toolkit reports UTXO token types under `token_type`, in the same hex
        // encoding the indexer reports as `tokenType`; if this probe ever skips a
        // provisioned environment, compare the two encodings first.
        const walletState = await scenario.toolkit.showPublicWalletState(
          scenario.wallet.source.address,
        );
        const spendable = walletState.utxos
          .filter((utxo) => utxo.token_type === CUSTOM_TOKEN_TYPE)
          .reduce((total, utxo) => total + utxo.value, 0);
        log.debug(`Funding wallet holds ${spendable} of custom token ${CUSTOM_TOKEN_TYPE}`);

        // Strictly greater: the transfer has to leave change behind, so that it creates
        // a destination output and a source output just as the NIGHT transfer does.
        return spendable > TRANSFER_AMOUNT
          ? null
          : `environment not provisioned: the funding wallet holds ${spendable} of custom unshielded token ${CUSTOM_TOKEN_TYPE}, which is not enough to transfer ${TRANSFER_AMOUNT} and leave change`;
      },
    });

    defineUnshieldedTransferTests(scenario);
  },
);
