name: build-wallet-indexer

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest-16-core-x64
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        env:
          toolchain_toml: "rust-toolchain.toml"
        run: |
          toolchain=$(grep channel rust-toolchain.toml | sed -r 's/channel = "(.*)"/\1/')
          echo "toolchain=$toolchain" | tee -a $GITHUB_ENV
          version=$(grep '^version.*=' Cargo.toml | sed -E 's/version.*=.*"(.*)"/\1/')
          echo "version=$version" | tee -a $GITHUB_ENV

      - name: Add github.com credentials to netrc
        uses: extractions/netrc@v2
        with:
          machine: github.com
          username: MidnightCI
          password: ${{ secrets.MIDNIGHTCI_REPO }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: MidnightCI
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Prepare metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 8
        with:
          images: ghcr.io/midnight-ntwrk/wallet-indexer
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=${{env.version}}-,format=short
            type=raw,value=latest
          labels: |
            org.opencontainers.image.source=https://github.com/midnight-ntwrk/artifacts
            org.opencontainers.image.title=wallet-indexer
            org.opencontainers.image.description=Midnight Wallet Indexer

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: wallet-indexer/Dockerfile
          push: true
          build-args: RUST_VERSION=${{env.toolchain}}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secret-files: netrc=/home/runner/.netrc
          cache-from: type=registry,ref=ghcr.io/midnight-ntwrk/wallet-indexer:buildcache
          cache-to: type=registry,ref=ghcr.io/midnight-ntwrk/wallet-indexer:buildcache,mode=max
